#!/usr/bin/env bash

TARGET=move_stacks
TEST_INPUT=test/test_input.txt
INPUT=input.txt

fail()
{
  echo $1
  exit 1
}
[ -f $TARGET ] || fail "$TARGET not found"
[ -x $TARGET ] || fail "$TARGET is not executable"
[ -f $TEST_INPUT ] || fail "$TEST_INPUT not found"

test_stack_output=$(./$TARGET $TEST_INPUT)
[ "$test_stack_output" = "CMZ" ] || fail "${TEST_INPUT}: Expected CMZ, got $test_stack_output"

test_stack_output=$(./$TARGET $INPUT)
[ "$test_stack_output" = "CNSZFDVLJ" ] || fail "${TEST_INPUT}: Expected CNSZFDVLJ, got $test_stack_output"

test_stack_output=$(./$TARGET --updated_mover $TEST_INPUT)
[ "$test_stack_output" = "MCD" ] || fail "${TEST_INPUT}: Expected MCD, got $test_stack_output"

test_stack_output=$(./$TARGET --updated_mover $INPUT)
[ "$test_stack_output" = "QNDWLMGNS" ] || fail "${TEST_INPUT}: Expected CNSZFDVLJ, got $test_stack_output"

echo "All system tests passed"
